name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run : docker build -t yashsojitra/gymbuddy-nodejs .

      - name: Publish Image to Docker hub
        run: docker push yashsojitra/gymbuddy-nodejs:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull and run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: yashsojitra/gymbuddy-nodejs:latest
          options: -d --name nodejs-app-container -p 4000:4000 \
                   -e MONGO_URI='${{secrets.MONGO_URI}}' \
                   -e PORT='${{secrets.PORT}}'
          run: node server.js