name: Deploy Node Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run : docker build -t yashsojitra/gymbuddy-nodejs .

      - name: Publish Image to Docker hub
        run: docker push yashsojitra/gymbuddy-nodejs:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Get Host IP Address
        run: |
          HOST_IP=$(curl -s ifconfig.me)
          echo "Host IP Address: $HOST_IP"
          echo "HOST_IP=$HOST_IP" >> $GITHUB_ENV

      - name: Stop previous running container if exists
        run: |
          if [ "$(docker ps -q -f name=nodejs-app-container)" ]; then
            docker stop nodejs-app-container
          fi
      
      - name: Remove previous container if exists
        run: |
          if [ "$(docker ps -a -q -f name=nodejs-app-container)" ]; then
            docker rm nodejs-app-container
          fi
              
      - name: Pull image from docker hub
        run: docker pull yashsojitra/gymbuddy-nodejs:latest

      - name: run docker container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_URI='${{secrets.MONGO_URI}}' -e PORT=${{secrets.PORT}} -e MAIL='${{secrets.GMAIL}}' -e PASS='${{secrets.APP_PASSWORD}}' -e SECRET='${{secrets.SECRET}}' -e IP='${{env.HOST_IP}}' yashsojitra/gymbuddy-nodejs
